#!/usr/bin/env python3

import os
import sys
import shutil

def main():
    '''
    Entry point for the script. Installs wa to /usr/local/bin
    '''
    if os.geteuid() != 0:
        print("This script must be run as root")
        sys.exit(1)

    target_directory = '/usr/local/bin' # only supports Linux at the moment

    try:
        shutil.copy("wa.py", os.path.join(target_directory, "wa"))
        print("Installed wa to /usr/local/bin")
    except Exception as e:
        print(f"Error installing wa: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()

